name: Unit tests and coverage

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_shared_library:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Pull Submodule
        run: git submodule update --init --recursive
      - name: Build DLL & Set file name windows
        if: matrix.runs-on == 'windows-latest'
        shell: pwsh
        run: |
          .\build_scripts\cmake_build.bat -s
          echo "filename=uc_sgsim.dll" >> $env:GITHUB_ENV
      - name: Build Shared Library & Set file name ubuntu
        if: matrix.runs-on == 'ubuntu-latest'
        run: |
          sh ./build_scripts/cmake_build.sh -s
          echo "filename=uc_sgsim.so" >> "$GITHUB_ENV"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runs-on }}-shared-library
          path: ./uc_sgsim/c_core/${{ env.filename }}

  python_test:
    name: py-unittest
    runs-on: ubuntu-latest
    needs: build_shared_library
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        runs-on: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          if (Test-Path requirements-dev.txt) {
            pip install --upgrade pip
            pip install -r requirements-dev.txt
          }
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sed -i '/^[^#]/s/==.*//' requirements-dev.txt
          python -m pip install --upgrade pip
          if [ -f requirements.txt ];
          then pip install -r requirements-dev.txt;
          fi
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Move dll file (Windows)
        if: runner.os == 'Windows'
        run: mv ./uc_sgsim.dll ./uc_sgsim/c_core
      - name: Move so file (Linux)
        if: runner.os == 'Linux'
        run: mv ./uc_sgsim.so ./uc_sgsim/c_core
      - name: Run tests to generate coverage statistics
        run: |
          pytest -n auto --cov --cov-report xml:py_coverage.xml
      - uses: actions/upload-artifact@v4
        if: matrix.python-version  == '3.11' && matrix.runs-on == 'ubuntu-latest'
        with:
          name: python-coverage
          path: ./py_coverage.xml

  c_test:
    name: c-unittest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Pull Submodule
        run: git submodule update --init --recursive
      - name: Build native targets
        run: |
          cmake -S . -B build
          cmake --build build/ --config Release
      - name: Run tests to generate coverage statistics
        run: |
          cd build
          ./c_example.out
          ./test/unittest
          cd ..
      - name: Install LCOV
        shell: bash
        run: |
          sudo apt-get --assume-yes install lcov > /dev/null
      - name: lcov collection
        shell: bash
        run: |
          cd build
          lcov -c -d . -o cover.info
          cd ..
      - uses: actions/upload-artifact@v4
        with:
          name: c-coverage2
          path: |
            ./build/cover.info

  c_test_windows:
    name: c-unittest-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Pull Submodule
        run: git submodule update --init --recursive
      - name: build and test
        run: |
          .\build_scripts\cmake_build.bat

  python_coverage:
    name: codecov-py
    runs-on: ubuntu-latest
    needs: [python_test]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Upload Python coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: python-coverage/py_coverage.xml

  c_coverage:
    name: codecov-c
    runs-on: ubuntu-latest
    needs: [c_test]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Upload C coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: c-coverage2/cover.info
